# Generated by Django 5.2.2 on 2025-06-07 11:35

import core.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='about',
            field=models.TextField(verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время выдачи теста'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='theme',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='attedance',
            name='attedance_date',
            field=models.BooleanField(default=False, null=True, verbose_name='Отметка'),
        ),
        migrations.AlterField(
            model_name='attedance',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='attedance',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='attedance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.student', verbose_name='Ученик(-ца)'),
        ),
        migrations.AlterField(
            model_name='attedance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='attedance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='day',
            field=models.CharField(max_length=50, verbose_name='День (дни-недели)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название класса'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата добавления оценки'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(validators=[core.models.ValueValidator], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.student', verbose_name='Ученик(-ца)'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='title',
            field=models.CharField(max_length=3, verbose_name='Четверть (I, II, III, IV)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.dayofweek', verbose_name='День (дни-недели)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typesofsubject', verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Класс ученика(-цы)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Ученик(-ца)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='about',
            field=models.TextField(verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время выдачи задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='Преподаватль'),
        ),
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typesofsubject', verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(to='core.group', verbose_name='Классы которые обучает'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='core.subject', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель(-ница)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Текс'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время выдачи теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='test',
            name='link',
            field=models.TextField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='typesofsubject',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/', validators=[core.models.max_limit_size_upload], verbose_name='Аватарка'),
        ),
    ]
