# Generated by Django 5.2.2 on 2025-06-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quarter',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
